# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTM1MjVkZDdjZGJkN2IwYjM3ZDMwZDBjYmQzNjg3NWEzYjRmMGUxZjIyZmFjNjVmNjYyMjZiNDJjNjMwNWMwZTUyODI5YThlYmY2OWZkM2IzNDQ1YzA3ZTRmN2ZmYzgwZmM3OTVjMTA0MjU0NzBlMzA1NzgxMDUwMTJkZjg5NGY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
